# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77099936dfc78b2c59551de1e1b91c125e2df29d8c66d6efb55c780c0916a7ce91e9dff641a612f0c030c40acbd4ad3af013501b710a209bb183de9746160481

test:
  secret_key_base: f8dd52e40cd4a00cd3da0d35b8aa7f2ef0ba6460356481281fd3b4e175dbee2327b68a1dcb07c7fd174ac168a90e704713f5a49805e1e312dcf9f63917827ebd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
